        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:50 2016
        MODULE ADAPTIVE_LOOP__genmod
          INTERFACE 
            SUBROUTINE ADAPTIVE_LOOP
            END SUBROUTINE ADAPTIVE_LOOP
          END INTERFACE 
        END MODULE ADAPTIVE_LOOP__genmod
