        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:16 2016
        MODULE ADD_FREE_COND__genmod
          INTERFACE 
            SUBROUTINE ADD_FREE_COND(IND_PART,OK,NP)
              INTEGER(KIND=4) :: IND_PART(1:32)
              LOGICAL(KIND=4) :: OK(1:32)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE ADD_FREE_COND
          END INTERFACE 
        END MODULE ADD_FREE_COND__genmod
