        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE ALLOCATE_PEAK_PATCH_ARRAYS__genmod
          INTERFACE 
            SUBROUTINE ALLOCATE_PEAK_PATCH_ARRAYS
            END SUBROUTINE ALLOCATE_PEAK_PATCH_ARRAYS
          END INTERFACE 
        END MODULE ALLOCATE_PEAK_PATCH_ARRAYS__genmod
