        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:50 2016
        MODULE AMR_STEP__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE AMR_STEP(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE AMR_STEP
          END INTERFACE 
        END MODULE AMR_STEP__genmod
