        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE ANALYZE_PEAK_MEMORY__genmod
          INTERFACE 
            SUBROUTINE ANALYZE_PEAK_MEMORY
              USE AMR_COMMONS
            END SUBROUTINE ANALYZE_PEAK_MEMORY
          END INTERFACE 
        END MODULE ANALYZE_PEAK_MEMORY__genmod
