        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:53 2016
        MODULE AUTHORIZE_COARSE__genmod
          INTERFACE 
            SUBROUTINE AUTHORIZE_COARSE
            END SUBROUTINE AUTHORIZE_COARSE
          END INTERFACE 
        END MODULE AUTHORIZE_COARSE__genmod
