        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:53 2016
        MODULE AUTHORIZE_FINE__genmod
          INTERFACE 
            SUBROUTINE AUTHORIZE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE AUTHORIZE_FINE
          END INTERFACE 
        END MODULE AUTHORIZE_FINE__genmod
