        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE BACKUP_SINK__genmod
          INTERFACE 
            SUBROUTINE BACKUP_SINK(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE BACKUP_SINK
          END INTERFACE 
        END MODULE BACKUP_SINK__genmod
