        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE BACKUP_AMR__genmod
          INTERFACE 
            SUBROUTINE BACKUP_AMR(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE BACKUP_AMR
          END INTERFACE 
        END MODULE BACKUP_AMR__genmod
