        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:28 2016
        MODULE BINARY_SEARCH__genmod
          INTERFACE 
            SUBROUTINE BINARY_SEARCH(DATABASE,XTARGET,NDATA,I)
              INTEGER(KIND=4), INTENT(IN) :: NDATA
              REAL(KIND=8), INTENT(IN) :: DATABASE(1:NDATA)
              REAL(KIND=8), INTENT(IN) :: XTARGET
              INTEGER(KIND=4) :: I
            END SUBROUTINE BINARY_SEARCH
          END INTERFACE 
        END MODULE BINARY_SEARCH__genmod
