        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE BOUNDARY_PEAK_INT__genmod
          INTERFACE 
            SUBROUTINE BOUNDARY_PEAK_INT(XX)
              USE CLFIND_COMMONS
              USE AMR_COMMONS
              INTEGER(KIND=4) :: XX(1:NPEAKS_MAX)
            END SUBROUTINE BOUNDARY_PEAK_INT
          END INTERFACE 
        END MODULE BOUNDARY_PEAK_INT__genmod
