        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE BUILD_PARENT_COMMS_MG__genmod
          INTERFACE 
            SUBROUTINE BUILD_PARENT_COMMS_MG(ACTIVE_F_COMM,IFINELEVEL)
              USE AMR_COMMONS
              TYPE (COMMUNICATOR), INTENT(IN) :: ACTIVE_F_COMM
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE BUILD_PARENT_COMMS_MG
          END INTERFACE 
        END MODULE BUILD_PARENT_COMMS_MG__genmod
