        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE BUILD_PEAK_COMMUNICATOR__genmod
          INTERFACE 
            SUBROUTINE BUILD_PEAK_COMMUNICATOR
              USE AMR_COMMONS
            END SUBROUTINE BUILD_PEAK_COMMUNICATOR
          END INTERFACE 
        END MODULE BUILD_PEAK_COMMUNICATOR__genmod
