        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:18 2016
        MODULE CHECK_TREE__genmod
          INTERFACE 
            SUBROUTINE CHECK_TREE(IND_GRID,IND_PART,IND_GRID_PART,NG,NP,&
     &ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: IND_PART(1:32)
              INTEGER(KIND=4) :: IND_GRID_PART(1:32)
              INTEGER(KIND=4) :: NG
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CHECK_TREE
          END INTERFACE 
        END MODULE CHECK_TREE__genmod
