        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:11 2016
        MODULE CIC_FROM_MULTIPOLE__genmod
          INTERFACE 
            SUBROUTINE CIC_FROM_MULTIPOLE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CIC_FROM_MULTIPOLE
          END INTERFACE 
        END MODULE CIC_FROM_MULTIPOLE__genmod
