        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:11 2016
        MODULE CIC_CELL__genmod
          INTERFACE 
            SUBROUTINE CIC_CELL(IND_GRID,NGRID,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CIC_CELL
          END INTERFACE 
        END MODULE CIC_CELL__genmod
