        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE CLEANUP_MG_LEVEL__genmod
          INTERFACE 
            SUBROUTINE CLEANUP_MG_LEVEL(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE CLEANUP_MG_LEVEL
          END INTERFACE 
        END MODULE CLEANUP_MG_LEVEL__genmod
