        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE CLEAN_STOP__genmod
          INTERFACE 
            SUBROUTINE CLEAN_STOP
            END SUBROUTINE CLEAN_STOP
          END INTERFACE 
        END MODULE CLEAN_STOP__genmod
