        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE CLUMP_FINDER__genmod
          INTERFACE 
            SUBROUTINE CLUMP_FINDER(CREATE_OUTPUT,KEEP_ALIVE)
              USE AMR_COMMONS
              LOGICAL(KIND=4) :: CREATE_OUTPUT
              LOGICAL(KIND=4) :: KEEP_ALIVE
            END SUBROUTINE CLUMP_FINDER
          END INTERFACE 
        END MODULE CLUMP_FINDER__genmod
