        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE CMP_UVAR_NORM2_COARSE__genmod
          INTERFACE 
            SUBROUTINE CMP_UVAR_NORM2_COARSE(IVAR,ILEVEL,NORM2)
              INTEGER(KIND=4), INTENT(IN) :: IVAR
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              REAL(KIND=8), INTENT(OUT) :: NORM2
            END SUBROUTINE CMP_UVAR_NORM2_COARSE
          END INTERFACE 
        END MODULE CMP_UVAR_NORM2_COARSE__genmod
