        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE CMP_RESIDUAL_MG__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_MG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE CMP_RESIDUAL_MG
          END INTERFACE 
        END MODULE CMP_RESIDUAL_MG__genmod
