        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:31 2016
        MODULE CMP_RESIDUAL_CG__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_CG(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE CMP_RESIDUAL_CG
          END INTERFACE 
        END MODULE CMP_RESIDUAL_CG__genmod
