        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:57 2016
        MODULE CMP_MINMAXORDER__genmod
          INTERFACE 
            SUBROUTINE CMP_MINMAXORDER(X,ORDER_MIN,ORDER_MAX,DX,NN)
              REAL(KIND=8) :: X(1:32,1:3)
              REAL(KIND=16) :: ORDER_MIN(1:32)
              REAL(KIND=16) :: ORDER_MAX(1:32)
              REAL(KIND=8) :: DX
              INTEGER(KIND=4) :: NN
            END SUBROUTINE CMP_MINMAXORDER
          END INTERFACE 
        END MODULE CMP_MINMAXORDER__genmod
