        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:28 2016
        MODULE CMP_STELLAR_WIND_PROPS__genmod
          INTERFACE 
            SUBROUTINE CMP_STELLAR_WIND_PROPS(BIRTH_TIME,DTEFF,ZSTAR,   &
     &DFMLOSS,LOG_DELOSS_ERG,DFMZLOSS,DFMLOSS_SPEC)
              REAL(KIND=8), INTENT(IN) :: BIRTH_TIME
              REAL(KIND=8), INTENT(IN) :: DTEFF
              REAL(KIND=8), INTENT(IN) :: ZSTAR
              REAL(KIND=8) :: DFMLOSS
              REAL(KIND=8) :: LOG_DELOSS_ERG
              REAL(KIND=8) :: DFMZLOSS
              REAL(KIND=8) :: DFMLOSS_SPEC(1:8)
            END SUBROUTINE CMP_STELLAR_WIND_PROPS
          END INTERFACE 
        END MODULE CMP_STELLAR_WIND_PROPS__genmod
