        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE CMP_RESIDUAL_MG_COARSE__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_MG_COARSE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE CMP_RESIDUAL_MG_COARSE
          END INTERFACE 
        END MODULE CMP_RESIDUAL_MG_COARSE__genmod
