        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE CMP_RESIDUAL_MG_FINE__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_MG_FINE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE CMP_RESIDUAL_MG_FINE
          END INTERFACE 
        END MODULE CMP_RESIDUAL_MG_FINE__genmod
