        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:57 2016
        MODULE CMP_NEW_CPU_MAP__genmod
          INTERFACE 
            SUBROUTINE CMP_NEW_CPU_MAP
              USE AMR_COMMONS
            END SUBROUTINE CMP_NEW_CPU_MAP
          END INTERFACE 
        END MODULE CMP_NEW_CPU_MAP__genmod
