        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE CMP_RESIDUAL_NORM2_FINE__genmod
          INTERFACE 
            SUBROUTINE CMP_RESIDUAL_NORM2_FINE(ILEVEL,NORM2)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              REAL(KIND=8), INTENT(OUT) :: NORM2
            END SUBROUTINE CMP_RESIDUAL_NORM2_FINE
          END INTERFACE 
        END MODULE CMP_RESIDUAL_NORM2_FINE__genmod
