        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:57 2016
        MODULE CMP_ORDERING__genmod
          INTERFACE 
            SUBROUTINE CMP_ORDERING(X,ORDER,NN)
              REAL(KIND=8) :: X(1:32,1:3)
              REAL(KIND=16) :: ORDER(1:32)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE CMP_ORDERING
          END INTERFACE 
        END MODULE CMP_ORDERING__genmod
