        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE COLLECT_ACCZONE_AVG__genmod
          INTERFACE 
            SUBROUTINE COLLECT_ACCZONE_AVG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COLLECT_ACCZONE_AVG
          END INTERFACE 
        END MODULE COLLECT_ACCZONE_AVG__genmod
