        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE COLLECT_ACCZONE_AVG_NP__genmod
          INTERFACE 
            SUBROUTINE COLLECT_ACCZONE_AVG_NP(IND_GRID,IND_PART,        &
     &IND_GRID_PART,NG,NP,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: IND_PART(1:32)
              INTEGER(KIND=4) :: IND_GRID_PART(1:32)
              INTEGER(KIND=4) :: NG
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COLLECT_ACCZONE_AVG_NP
          END INTERFACE 
        END MODULE COLLECT_ACCZONE_AVG_NP__genmod
