        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:06 2016
        MODULE COMPUTE_CENTRAL__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_CENTRAL(A,W,NN)
              REAL(KIND=8) :: A(1:32,0:6)
              REAL(KIND=8) :: W(1:32,1:3)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE COMPUTE_CENTRAL
          END INTERFACE 
        END MODULE COMPUTE_CENTRAL__genmod
