        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:26 2016
        MODULE COMPUTE_NCLOUD_SINK__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_NCLOUD_SINK
            END SUBROUTINE COMPUTE_NCLOUD_SINK
          END INTERFACE 
        END MODULE COMPUTE_NCLOUD_SINK__genmod
