        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE COMPUTE_ACCRETION_RATE__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_ACCRETION_RATE(WRITE_SINKS)
              USE PM_COMMONS
              LOGICAL(KIND=4) :: WRITE_SINKS
            END SUBROUTINE COMPUTE_ACCRETION_RATE
          END INTERFACE 
        END MODULE COMPUTE_ACCRETION_RATE__genmod
