        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE COMPUTE_CLUMP_PROPERTIES_ROUND2__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_CLUMP_PROPERTIES_ROUND2(XX)
              USE AMR_COMMONS
              USE PM_COMMONS, ONLY :                                    &
     &          CONT_SPEED
              USE CLFIND_COMMONS
              REAL(KIND=8) :: XX(1:NCOARSE+NGRIDMAX*8)
            END SUBROUTINE COMPUTE_CLUMP_PROPERTIES_ROUND2
          END INTERFACE 
        END MODULE COMPUTE_CLUMP_PROPERTIES_ROUND2__genmod
