        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:59 2016
        MODULE COMPUTE_ROTATION_MATRIX__genmod
          INTERFACE 
            SUBROUTINE COMPUTE_ROTATION_MATRIX(THETASHIFTRAD,PHISHIFTRAD&
     &,ROT,ROTM1)
              REAL(KIND=8) :: THETASHIFTRAD
              REAL(KIND=8) :: PHISHIFTRAD
              REAL(KIND=8) :: ROT(3,3)
              REAL(KIND=8) :: ROTM1(3,3)
            END SUBROUTINE COMPUTE_ROTATION_MATRIX
          END INTERFACE 
        END MODULE COMPUTE_ROTATION_MATRIX__genmod
