        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:58 2016
        MODULE COOLING_FINE__genmod
          INTERFACE 
            SUBROUTINE COOLING_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COOLING_FINE
          END INTERFACE 
        END MODULE COOLING_FINE__genmod
