        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:58 2016
        MODULE COOLFINE1__genmod
          INTERFACE 
            SUBROUTINE COOLFINE1(IND_GRID,NGRID,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COOLFINE1
          END INTERFACE 
        END MODULE COOLFINE1__genmod
