        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:59 2016
        MODULE COORD_DISTANCE__genmod
          INTERFACE 
            FUNCTION COORD_DISTANCE(ZZ,OMEGA0,OMEGAL,OMEGAR,COVERH0)
              REAL(KIND=8) :: ZZ
              REAL(KIND=8) :: OMEGA0
              REAL(KIND=8) :: OMEGAL
              REAL(KIND=8) :: OMEGAR
              REAL(KIND=8) :: COVERH0
              REAL(KIND=8) :: COORD_DISTANCE
            END FUNCTION COORD_DISTANCE
          END INTERFACE 
        END MODULE COORD_DISTANCE__genmod
