        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE COUNT_PARTS__genmod
          INTERFACE 
            SUBROUTINE COUNT_PARTS
              USE PM_COMMONS
            END SUBROUTINE COUNT_PARTS
          END INTERFACE 
        END MODULE COUNT_PARTS__genmod
