        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE COUNT_CLOUDS__genmod
          INTERFACE 
            SUBROUTINE COUNT_CLOUDS(ILEVEL,ACTION)
              INTEGER(KIND=4) :: ILEVEL
              CHARACTER(LEN=15) :: ACTION
            END SUBROUTINE COUNT_CLOUDS
          END INTERFACE 
        END MODULE COUNT_CLOUDS__genmod
