        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE COUNT_NBORS2__genmod
          INTERFACE 
            SUBROUTINE COUNT_NBORS2(IGRIDN,IND,N_NBOR,NN)
              INTEGER(KIND=4) :: IGRIDN(1:32,0:6)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: N_NBOR
              INTEGER(KIND=4) :: NN
            END SUBROUTINE COUNT_NBORS2
          END INTERFACE 
        END MODULE COUNT_NBORS2__genmod
