        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:01 2016
        MODULE COURANT_FINE__genmod
          INTERFACE 
            SUBROUTINE COURANT_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE COURANT_FINE
          END INTERFACE 
        END MODULE COURANT_FINE__genmod
