        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE CREATE_SINK__genmod
          INTERFACE 
            SUBROUTINE CREATE_SINK
            END SUBROUTINE CREATE_SINK
          END INTERFACE 
        END MODULE CREATE_SINK__genmod
