        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE CREATE_CLOUD_FROM_SINK__genmod
          INTERFACE 
            SUBROUTINE CREATE_CLOUD_FROM_SINK
            END SUBROUTINE CREATE_CLOUD_FROM_SINK
          END INTERFACE 
        END MODULE CREATE_CLOUD_FROM_SINK__genmod
