        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:19 2016
        MODULE EMPTY_COMM__genmod
          INTERFACE 
            SUBROUTINE EMPTY_COMM(IND_COM,NP,ILEVEL,ICPU)
              INTEGER(KIND=4) :: IND_COM(1:32)
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICPU
            END SUBROUTINE EMPTY_COMM
          END INTERFACE 
        END MODULE EMPTY_COMM__genmod
