        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE ENSURE_REF_RULES__genmod
          INTERFACE 
            SUBROUTINE ENSURE_REF_RULES(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE ENSURE_REF_RULES
          END INTERFACE 
        END MODULE ENSURE_REF_RULES__genmod
