        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE F_SINK_SINK__genmod
          INTERFACE 
            SUBROUTINE F_SINK_SINK
            END SUBROUTINE F_SINK_SINK
          END INTERFACE 
        END MODULE F_SINK_SINK__genmod
