        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:01 2016
        MODULE FILE_DESCRIPTOR_HYDRO__genmod
          INTERFACE 
            SUBROUTINE FILE_DESCRIPTOR_HYDRO(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE FILE_DESCRIPTOR_HYDRO
          END INTERFACE 
        END MODULE FILE_DESCRIPTOR_HYDRO__genmod
