        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE FLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE FLAG_FINE(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE FLAG_FINE
          END INTERFACE 
        END MODULE FLAG_FINE__genmod
