        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE FLAG_PEAKS__genmod
          INTERFACE 
            SUBROUTINE FLAG_PEAKS(XX,IPEAK)
              USE AMR_COMMONS
              REAL(KIND=8) :: XX(1:NCOARSE+NGRIDMAX*8)
              INTEGER(KIND=4) :: IPEAK
            END SUBROUTINE FLAG_PEAKS
          END INTERFACE 
        END MODULE FLAG_PEAKS__genmod
