        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE FLAG_COARSE__genmod
          INTERFACE 
            SUBROUTINE FLAG_COARSE
            END SUBROUTINE FLAG_COARSE
          END INTERFACE 
        END MODULE FLAG_COARSE__genmod
