        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE FLAG_FORMATION_SITES__genmod
          INTERFACE 
            SUBROUTINE FLAG_FORMATION_SITES
              USE CLFIND_COMMONS
            END SUBROUTINE FLAG_FORMATION_SITES
          END INTERFACE 
        END MODULE FLAG_FORMATION_SITES__genmod
