        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE FULL_MULTIGRID__genmod
          INTERFACE 
            SUBROUTINE FULL_MULTIGRID(ICOUNT)
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE FULL_MULTIGRID
          END INTERFACE 
        END MODULE FULL_MULTIGRID__genmod
