        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE GAUSS_SEIDEL_MG_COARSE__genmod
          INTERFACE 
            SUBROUTINE GAUSS_SEIDEL_MG_COARSE(ILEVEL,SAFE,REDSTEP)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              LOGICAL(KIND=4), INTENT(IN) :: SAFE
              LOGICAL(KIND=4), INTENT(IN) :: REDSTEP
            END SUBROUTINE GAUSS_SEIDEL_MG_COARSE
          END INTERFACE 
        END MODULE GAUSS_SEIDEL_MG_COARSE__genmod
