        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE GAUSS_SEIDEL_MG_FINE__genmod
          INTERFACE 
            SUBROUTINE GAUSS_SEIDEL_MG_FINE(ILEVEL,REDSTEP)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              LOGICAL(KIND=4), INTENT(IN) :: REDSTEP
            END SUBROUTINE GAUSS_SEIDEL_MG_FINE
          END INTERFACE 
        END MODULE GAUSS_SEIDEL_MG_FINE__genmod
