        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE GAUSS_SEIDEL__genmod
          INTERFACE 
            SUBROUTINE GAUSS_SEIDEL(ILEVEL,REDSTEP)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: REDSTEP
            END SUBROUTINE GAUSS_SEIDEL
          END INTERFACE 
        END MODULE GAUSS_SEIDEL__genmod
