        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE GET_LOCAL_PEAK_ID__genmod
          INTERFACE 
            SUBROUTINE GET_LOCAL_PEAK_ID(GLOBAL_PEAK_ID,LOCAL_PEAK_ID)
              INTEGER(KIND=4) :: GLOBAL_PEAK_ID
              INTEGER(KIND=4) :: LOCAL_PEAK_ID
            END SUBROUTINE GET_LOCAL_PEAK_ID
          END INTERFACE 
        END MODULE GET_LOCAL_PEAK_ID__genmod
