        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:30 2016
        MODULE GET_NUMBER_OF_SNIA__genmod
          INTERFACE 
            SUBROUTINE GET_NUMBER_OF_SNIA(BIRTH_TIME,DTEFF,ID_STAR,MASS0&
     &,NSNIA)
              REAL(KIND=8) :: BIRTH_TIME
              REAL(KIND=8) :: DTEFF
              INTEGER(KIND=4) :: ID_STAR
              REAL(KIND=8) :: MASS0
              REAL(KIND=8) :: NSNIA
            END SUBROUTINE GET_NUMBER_OF_SNIA
          END INTERFACE 
        END MODULE GET_NUMBER_OF_SNIA__genmod
