        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:29 2016
        MODULE GET_NUMBER_OF_SN2__genmod
          INTERFACE 
            SUBROUTINE GET_NUMBER_OF_SN2(BIRTH_TIME,DTEFF,ZP_STAR,      &
     &ID_STAR,MASS0,NSN,DONE_STAR)
              REAL(KIND=8) :: BIRTH_TIME
              REAL(KIND=8) :: DTEFF
              REAL(KIND=8) :: ZP_STAR
              INTEGER(KIND=4) :: ID_STAR
              REAL(KIND=8) :: MASS0
              REAL(KIND=8) :: NSN
              LOGICAL(KIND=4) :: DONE_STAR
            END SUBROUTINE GET_NUMBER_OF_SN2
          END INTERFACE 
        END MODULE GET_NUMBER_OF_SN2__genmod
