        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE GET_CELL_CENTER__genmod
          INTERFACE 
            SUBROUTINE GET_CELL_CENTER(XX,INDEX,ILEVEL)
              REAL(KIND=8) :: XX(1:3)
              INTEGER(KIND=4) :: INDEX
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GET_CELL_CENTER
          END INTERFACE 
        END MODULE GET_CELL_CENTER__genmod
