        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:29 2016
        MODULE GET_ICELL_FROM_POS__genmod
          INTERFACE 
            SUBROUTINE GET_ICELL_FROM_POS(FPOS,ILEVEL_MAX,IND_GRID,     &
     &IND_CELL,ILEVEL_OUT)
              REAL(KIND=8) :: FPOS(1:3)
              INTEGER(KIND=4) :: ILEVEL_MAX
              INTEGER(KIND=4) :: IND_GRID
              INTEGER(KIND=4) :: IND_CELL
              INTEGER(KIND=4) :: ILEVEL_OUT
            END SUBROUTINE GET_ICELL_FROM_POS
          END INTERFACE 
        END MODULE GET_ICELL_FROM_POS__genmod
