        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE GETAGEGYR__genmod
          INTERFACE 
            SUBROUTINE GETAGEGYR(T_BIRTH_PROPER,AGE)
              REAL(KIND=8) :: T_BIRTH_PROPER
              REAL(KIND=8) :: AGE
            END SUBROUTINE GETAGEGYR
          END INTERFACE 
        END MODULE GETAGEGYR__genmod
