        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE GETAGESEC__genmod
          INTERFACE 
            SUBROUTINE GETAGESEC(T_BIRTH_PROPER,AGE)
              REAL(KIND=8) :: T_BIRTH_PROPER
              REAL(KIND=8) :: AGE
            END SUBROUTINE GETAGESEC
          END INTERFACE 
        END MODULE GETAGESEC__genmod
