        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:56 2016
        MODULE GETINDICES3CUBE__genmod
          INTERFACE 
            SUBROUTINE GETINDICES3CUBE(LLL,MMM)
              INTEGER(KIND=4) :: LLL(1:27,1:8,1:3)
              INTEGER(KIND=4) :: MMM(1:27,1:8,1:3)
            END SUBROUTINE GETINDICES3CUBE
          END INTERFACE 
        END MODULE GETINDICES3CUBE__genmod
