        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE GETICELL99__genmod
          INTERFACE 
            SUBROUTINE GETICELL99(ICELL,ICD,NP)
              INTEGER(KIND=4) :: ICELL(1:99)
              INTEGER(KIND=4) :: ICD(1:99,1:3)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE GETICELL99
          END INTERFACE 
        END MODULE GETICELL99__genmod
