        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE GETICELL__genmod
          INTERFACE 
            SUBROUTINE GETICELL(ICELL,ICD,NP)
              INTEGER(KIND=4) :: ICELL(1:32)
              INTEGER(KIND=4) :: ICD(1:32,1:3)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE GETICELL
          END INTERFACE 
        END MODULE GETICELL__genmod
