        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:56 2016
        MODULE GETNBORGRIDS_CHECK__genmod
          INTERFACE 
            SUBROUTINE GETNBORGRIDS_CHECK(IGRID,IGRIDN,NGRID)
              INTEGER(KIND=4) :: IGRID(1:32)
              INTEGER(KIND=4) :: IGRIDN(1:32,0:6)
              INTEGER(KIND=4) :: NGRID
            END SUBROUTINE GETNBORGRIDS_CHECK
          END INTERFACE 
        END MODULE GETNBORGRIDS_CHECK__genmod
