        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:56 2016
        MODULE GETNBORCELLS__genmod
          INTERFACE 
            SUBROUTINE GETNBORCELLS(IGRIDN,IND,ICELLN,NG)
              INTEGER(KIND=4) :: IGRIDN(1:32,0:6)
              INTEGER(KIND=4) :: IND
              INTEGER(KIND=4) :: ICELLN(1:32,1:6)
              INTEGER(KIND=4) :: NG
            END SUBROUTINE GETNBORCELLS
          END INTERFACE 
        END MODULE GETNBORCELLS__genmod
