        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:17 2016
        MODULE GETNBOR__genmod
          INTERFACE 
            SUBROUTINE GETNBOR(IND_CELL,IND_FATHER,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:32)
              INTEGER(KIND=4) :: IND_FATHER(1:32,0:6)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GETNBOR
          END INTERFACE 
        END MODULE GETNBOR__genmod
