        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE GETPROPERTIME__genmod
          INTERFACE 
            SUBROUTINE GETPROPERTIME(TAU,TPROPER)
              REAL(KIND=8) :: TAU
              REAL(KIND=8) :: TPROPER
            END SUBROUTINE GETPROPERTIME
          END INTERFACE 
        END MODULE GETPROPERTIME__genmod
