        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:29 2016
        MODULE GETSTARAGEGYR__genmod
          INTERFACE 
            SUBROUTINE GETSTARAGEGYR(BIRTH_TIME,AGE_STAR)
              REAL(KIND=8) :: BIRTH_TIME
              REAL(KIND=8) :: AGE_STAR
            END SUBROUTINE GETSTARAGEGYR
          END INTERFACE 
        END MODULE GETSTARAGEGYR__genmod
