        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:02 2016
        MODULE GODFINE1__genmod
          INTERFACE 
            SUBROUTINE GODFINE1(IND_GRID,NCACHE,ILEVEL)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: NCACHE
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE GODFINE1
          END INTERFACE 
        END MODULE GODFINE1__genmod
