        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:32 2016
        MODULE GRADIENT_PHI__genmod
          INTERFACE 
            SUBROUTINE GRADIENT_PHI(IND_GRID,NGRID,ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE GRADIENT_PHI
          END INTERFACE 
        END MODULE GRADIENT_PHI__genmod
