        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE GROW_SINK__genmod
          INTERFACE 
            SUBROUTINE GROW_SINK(ILEVEL,ON_CREATION)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: ON_CREATION
            END SUBROUTINE GROW_SINK
          END INTERFACE 
        END MODULE GROW_SINK__genmod
