        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:56 2016
        MODULE HILBERT1D__genmod
          INTERFACE 
            SUBROUTINE HILBERT1D(X,ORDER,NPOINT)
              INTEGER(KIND=4), INTENT(IN) :: NPOINT
              INTEGER(KIND=4), INTENT(IN) :: X(1:NPOINT)
              REAL(KIND=16), INTENT(OUT) :: ORDER(1:NPOINT)
            END SUBROUTINE HILBERT1D
          END INTERFACE 
        END MODULE HILBERT1D__genmod
