        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:08 2016
        MODULE HYDRO_FLAG__genmod
          INTERFACE 
            SUBROUTINE HYDRO_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE HYDRO_FLAG
          END INTERFACE 
        END MODULE HYDRO_FLAG__genmod
