        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:49 2016
        MODULE INIT_TIME__genmod
          INTERFACE 
            SUBROUTINE INIT_TIME
            END SUBROUTINE INIT_TIME
          END INTERFACE 
        END MODULE INIT_TIME__genmod
