        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:49 2016
        MODULE INIT_COSMO__genmod
          INTERFACE 
            SUBROUTINE INIT_COSMO
            END SUBROUTINE INIT_COSMO
          END INTERFACE 
        END MODULE INIT_COSMO__genmod
