        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE INIT_BOUNDARY_COARSE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDARY_COARSE
            END SUBROUTINE INIT_BOUNDARY_COARSE
          END INTERFACE 
        END MODULE INIT_BOUNDARY_COARSE__genmod
