        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:28 2016
        MODULE INIT_STELLAR_WINDS__genmod
          INTERFACE 
            SUBROUTINE INIT_STELLAR_WINDS
            END SUBROUTINE INIT_STELLAR_WINDS
          END INTERFACE 
        END MODULE INIT_STELLAR_WINDS__genmod
