        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:00 2016
        MODULE INIT_FLOW__genmod
          INTERFACE 
            SUBROUTINE INIT_FLOW
            END SUBROUTINE INIT_FLOW
          END INTERFACE 
        END MODULE INIT_FLOW__genmod
