        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:50 2016
        MODULE INIT_REFINE_2__genmod
          INTERFACE 
            SUBROUTINE INIT_REFINE_2
            END SUBROUTINE INIT_REFINE_2
          END INTERFACE 
        END MODULE INIT_REFINE_2__genmod
