        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:00 2016
        MODULE INIT_HYDRO__genmod
          INTERFACE 
            SUBROUTINE INIT_HYDRO
            END SUBROUTINE INIT_HYDRO
          END INTERFACE 
        END MODULE INIT_HYDRO__genmod
