        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:00 2016
        MODULE INIT_FLOW_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_FLOW_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_FLOW_FINE
          END INTERFACE 
        END MODULE INIT_FLOW_FINE__genmod
