        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE INIT_REFMAP__genmod
          INTERFACE 
            SUBROUTINE INIT_REFMAP
            END SUBROUTINE INIT_REFMAP
          END INTERFACE 
        END MODULE INIT_REFMAP__genmod
