        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:53 2016
        MODULE INIT_BOUNDARY_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_BOUNDARY_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_BOUNDARY_FINE
          END INTERFACE 
        END MODULE INIT_BOUNDARY_FINE__genmod
