        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE INIT_FLAG__genmod
          INTERFACE 
            SUBROUTINE INIT_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_FLAG
          END INTERFACE 
        END MODULE INIT_FLAG__genmod
