        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE INIT_REFMAP_FINE__genmod
          INTERFACE 
            SUBROUTINE INIT_REFMAP_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE INIT_REFMAP_FINE
          END INTERFACE 
        END MODULE INIT_REFMAP_FINE__genmod
