        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:49 2016
        MODULE INIT_FILE__genmod
          INTERFACE 
            SUBROUTINE INIT_FILE
            END SUBROUTINE INIT_FILE
          END INTERFACE 
        END MODULE INIT_FILE__genmod
