        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:26 2016
        MODULE INIT_SINK__genmod
          INTERFACE 
            SUBROUTINE INIT_SINK
            END SUBROUTINE INIT_SINK
          END INTERFACE 
        END MODULE INIT_SINK__genmod
