        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:48 2016
        MODULE INIT_SNIA_YIELD__genmod
          INTERFACE 
            SUBROUTINE INIT_SNIA_YIELD
            END SUBROUTINE INIT_SNIA_YIELD
          END INTERFACE 
        END MODULE INIT_SNIA_YIELD__genmod
