        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:48 2016
        MODULE INIT_MECHANICAL__genmod
          INTERFACE 
            SUBROUTINE INIT_MECHANICAL
            END SUBROUTINE INIT_MECHANICAL
          END INTERFACE 
        END MODULE INIT_MECHANICAL__genmod
