        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:50 2016
        MODULE INIT_REFINE__genmod
          INTERFACE 
            SUBROUTINE INIT_REFINE
            END SUBROUTINE INIT_REFINE
          END INTERFACE 
        END MODULE INIT_REFINE__genmod
