        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:31 2016
        MODULE INIT_POISSON__genmod
          INTERFACE 
            SUBROUTINE INIT_POISSON
            END SUBROUTINE INIT_POISSON
          END INTERFACE 
        END MODULE INIT_POISSON__genmod
