        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:06 2016
        MODULE INTERPOL_HYDRO__genmod
          INTERFACE 
            SUBROUTINE INTERPOL_HYDRO(U1,U2,NN)
              REAL(KIND=8) :: U1(1:32,0:6,1:15)
              REAL(KIND=8) :: U2(1:32,1:8,1:15)
              INTEGER(KIND=4) :: NN
            END SUBROUTINE INTERPOL_HYDRO
          END INTERFACE 
        END MODULE INTERPOL_HYDRO__genmod
