        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE INTERPOLATE_AND_CORRECT_COARSE__genmod
          INTERFACE 
            SUBROUTINE INTERPOLATE_AND_CORRECT_COARSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE INTERPOLATE_AND_CORRECT_COARSE
          END INTERFACE 
        END MODULE INTERPOLATE_AND_CORRECT_COARSE__genmod
