        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:08 2016
        MODULE JEANS_LENGTH_REFINE__genmod
          INTERFACE 
            SUBROUTINE JEANS_LENGTH_REFINE(IND_CELL,OK,NCELL,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:32)
              LOGICAL(KIND=4) :: OK(1:32)
              INTEGER(KIND=4) :: NCELL
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE JEANS_LENGTH_REFINE
          END INTERFACE 
        END MODULE JEANS_LENGTH_REFINE__genmod
