        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:18 2016
        MODULE KILL_TREE_FINE__genmod
          INTERFACE 
            SUBROUTINE KILL_TREE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE KILL_TREE_FINE
          END INTERFACE 
        END MODULE KILL_TREE_FINE__genmod
