        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE KILL_ENTIRE_CLOUD__genmod
          INTERFACE 
            SUBROUTINE KILL_ENTIRE_CLOUD(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE KILL_ENTIRE_CLOUD
          END INTERFACE 
        END MODULE KILL_ENTIRE_CLOUD__genmod
