        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:22 2016
        MODULE KINETIC_FEEDBACK__genmod
          INTERFACE 
            SUBROUTINE KINETIC_FEEDBACK
              USE AMR_COMMONS
            END SUBROUTINE KINETIC_FEEDBACK
          END INTERFACE 
        END MODULE KINETIC_FEEDBACK__genmod
