        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:57 2016
        MODULE LOAD_BALANCE__genmod
          INTERFACE 
            SUBROUTINE LOAD_BALANCE
              USE BISECTION
            END SUBROUTINE LOAD_BALANCE
          END INTERFACE 
        END MODULE LOAD_BALANCE__genmod
