        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:09 2016
        MODULE LOAD_GADGET__genmod
          INTERFACE 
            SUBROUTINE LOAD_GADGET
              USE AMR_COMMONS
            END SUBROUTINE LOAD_GADGET
          END INTERFACE 
        END MODULE LOAD_GADGET__genmod
