        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:31 2016
        MODULE MAKE_INITIAL_PHI__genmod
          INTERFACE 
            SUBROUTINE MAKE_INITIAL_PHI(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE MAKE_INITIAL_PHI
          END INTERFACE 
        END MODULE MAKE_INITIAL_PHI__genmod
