        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE MAKE_SINK_FROM_CLUMP__genmod
          INTERFACE 
            SUBROUTINE MAKE_SINK_FROM_CLUMP(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_SINK_FROM_CLUMP
          END INTERFACE 
        END MODULE MAKE_SINK_FROM_CLUMP__genmod
