        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE MAKE_FINE_MASK__genmod
          INTERFACE 
            SUBROUTINE MAKE_FINE_MASK(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE MAKE_FINE_MASK
          END INTERFACE 
        END MODULE MAKE_FINE_MASK__genmod
