        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:31 2016
        MODULE MAKE_MULTIPOLE_PHI__genmod
          INTERFACE 
            SUBROUTINE MAKE_MULTIPOLE_PHI(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_MULTIPOLE_PHI
          END INTERFACE 
        END MODULE MAKE_MULTIPOLE_PHI__genmod
