        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:37 2016
        MODULE MAKE_BOUNDARY_MASK__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_MASK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_BOUNDARY_MASK
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_MASK__genmod
