        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:53 2016
        MODULE MAKE_BOUNDARY_COARSE__genmod
          INTERFACE 
            SUBROUTINE MAKE_BOUNDARY_COARSE
            END SUBROUTINE MAKE_BOUNDARY_COARSE
          END INTERFACE 
        END MODULE MAKE_BOUNDARY_COARSE__genmod
