        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE MAKE_VIRTUAL_MG_INT__genmod
          INTERFACE 
            SUBROUTINE MAKE_VIRTUAL_MG_INT(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_VIRTUAL_MG_INT
          END INTERFACE 
        END MODULE MAKE_VIRTUAL_MG_INT__genmod
