        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE MAKE_REVERSE_MG_DP__genmod
          INTERFACE 
            SUBROUTINE MAKE_REVERSE_MG_DP(IVAR,ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: IVAR
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_REVERSE_MG_DP
          END INTERFACE 
        END MODULE MAKE_REVERSE_MG_DP__genmod
