        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:53 2016
        MODULE MAKE_VIRTUAL_REVERSE_INT__genmod
          INTERFACE 
            SUBROUTINE MAKE_VIRTUAL_REVERSE_INT(XX,ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: XX(1:NCOARSE+NGRIDMAX*8)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MAKE_VIRTUAL_REVERSE_INT
          END INTERFACE 
        END MODULE MAKE_VIRTUAL_REVERSE_INT__genmod
