        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:55 2016
        MODULE MAKE_GRID_COARSE__genmod
          INTERFACE 
            SUBROUTINE MAKE_GRID_COARSE(IND_CELL,IBOUND,BOUNDARY_REGION)
              INTEGER(KIND=4) :: IND_CELL
              INTEGER(KIND=4) :: IBOUND
              LOGICAL(KIND=4) :: BOUNDARY_REGION
            END SUBROUTINE MAKE_GRID_COARSE
          END INTERFACE 
        END MODULE MAKE_GRID_COARSE__genmod
