        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:30 2016
        MODULE MECH_FINE_SNIA_MPI__genmod
          INTERFACE 
            SUBROUTINE MECH_FINE_SNIA_MPI(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MECH_FINE_SNIA_MPI
          END INTERFACE 
        END MODULE MECH_FINE_SNIA_MPI__genmod
