        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:30 2016
        MODULE MECHANICAL_FEEDBACK_SNIA_FINE__genmod
          INTERFACE 
            SUBROUTINE MECHANICAL_FEEDBACK_SNIA_FINE(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE MECHANICAL_FEEDBACK_SNIA_FINE
          END INTERFACE 
        END MODULE MECHANICAL_FEEDBACK_SNIA_FINE__genmod
