        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE MERGE_STAR_SINK__genmod
          INTERFACE 
            SUBROUTINE MERGE_STAR_SINK
            END SUBROUTINE MERGE_STAR_SINK
          END INTERFACE 
        END MODULE MERGE_STAR_SINK__genmod
