        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE MERGE_SMBH_SINK__genmod
          INTERFACE 
            SUBROUTINE MERGE_SMBH_SINK
            END SUBROUTINE MERGE_SMBH_SINK
          END INTERFACE 
        END MODULE MERGE_SMBH_SINK__genmod
