        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE MERGE_CLUMPS__genmod
          INTERFACE 
            SUBROUTINE MERGE_CLUMPS(ACTION)
              USE CLFIND_COMMONS
              CHARACTER(LEN=9) :: ACTION
            END SUBROUTINE MERGE_CLUMPS
          END INTERFACE 
        END MODULE MERGE_CLUMPS__genmod
