        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:14 2016
        MODULE MOVE_FINE__genmod
          INTERFACE 
            SUBROUTINE MOVE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MOVE_FINE
          END INTERFACE 
        END MODULE MOVE_FINE__genmod
