        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:11 2016
        MODULE MULTIPOLE_FINE__genmod
          INTERFACE 
            SUBROUTINE MULTIPOLE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MULTIPOLE_FINE
          END INTERFACE 
        END MODULE MULTIPOLE_FINE__genmod
