        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE MULTIGRID_FINE__genmod
          INTERFACE 
            SUBROUTINE MULTIGRID_FINE(ILEVEL,ICOUNT)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
              INTEGER(KIND=4), INTENT(IN) :: ICOUNT
            END SUBROUTINE MULTIGRID_FINE
          END INTERFACE 
        END MODULE MULTIGRID_FINE__genmod
