        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE MULTIGRID_ITERATOR__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE MULTIGRID_ITERATOR(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE MULTIGRID_ITERATOR
          END INTERFACE 
        END MODULE MULTIGRID_ITERATOR__genmod
