        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE MULTIGRID_COARSE__genmod
          INTERFACE 
            SUBROUTINE MULTIGRID_COARSE(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE MULTIGRID_COARSE
          END INTERFACE 
        END MODULE MULTIGRID_COARSE__genmod
