        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:15 2016
        MODULE NEWDT_FINE__genmod
          INTERFACE 
            SUBROUTINE NEWDT_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE NEWDT_FINE
          END INTERFACE 
        END MODULE NEWDT_FINE__genmod
