        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:17 2016
        MODULE OPEN_STAT_FILES__genmod
          INTERFACE 
            SUBROUTINE OPEN_STAT_FILES
            END SUBROUTINE OPEN_STAT_FILES
          END INTERFACE 
        END MODULE OPEN_STAT_FILES__genmod
