        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE OUTPUT_HEADER__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_HEADER(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_HEADER
          END INTERFACE 
        END MODULE OUTPUT_HEADER__genmod
