        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE OUTPUT_INFO__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_INFO(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_INFO
          END INTERFACE 
        END MODULE OUTPUT_INFO__genmod
