        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 18 16:03:09 2016
        MODULE OUTPUT_PATCH__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_PATCH(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_PATCH
          END INTERFACE 
        END MODULE OUTPUT_PATCH__genmod
