        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:59 2016
        MODULE OUTPUT_CONE__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_CONE
            END SUBROUTINE OUTPUT_CONE
          END INTERFACE 
        END MODULE OUTPUT_CONE__genmod
