        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:59 2016
        MODULE OUTPUT_FRAME__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_FRAME
            END SUBROUTINE OUTPUT_FRAME
          END INTERFACE 
        END MODULE OUTPUT_FRAME__genmod
