        !COMPILER-GENERATED INTERFACE MODULE: Mon Jul 18 16:03:08 2016
        MODULE OUTPUT_MAKEFILE__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_MAKEFILE(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_MAKEFILE
          END INTERFACE 
        END MODULE OUTPUT_MAKEFILE__genmod
