        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE OUTPUT_SINK__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SINK(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_SINK
          END INTERFACE 
        END MODULE OUTPUT_SINK__genmod
