        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE OUTPUT_SINK_CSV__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SINK_CSV(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE OUTPUT_SINK_CSV
          END INTERFACE 
        END MODULE OUTPUT_SINK_CSV__genmod
