        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:38 2016
        MODULE OUTPUT_SIGNAL__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SIGNAL
            END SUBROUTINE OUTPUT_SIGNAL
          END INTERFACE 
        END MODULE OUTPUT_SIGNAL__genmod
