        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:22 2016
        MODULE OUTPUT_SN_STATS__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_SN_STATS
            END SUBROUTINE OUTPUT_SN_STATS
          END INTERFACE 
        END MODULE OUTPUT_SN_STATS__genmod
