        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:31 2016
        MODULE PHI_FINE_CG__genmod
          INTERFACE 
            SUBROUTINE PHI_FINE_CG(ILEVEL,ICOUNT)
              INTEGER(KIND=4) :: ILEVEL
              INTEGER(KIND=4) :: ICOUNT
            END SUBROUTINE PHI_FINE_CG
          END INTERFACE 
        END MODULE PHI_FINE_CG__genmod
