        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE PRINT_SINK_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE PRINT_SINK_PROPERTIES(DMEDOVERDT,RHO_INF,R2,     &
     &V_BONDI)
              USE PM_COMMONS
              REAL(KIND=8) :: DMEDOVERDT(1:NSINKMAX)
              REAL(KIND=8) :: RHO_INF
              REAL(KIND=8) :: R2
              REAL(KIND=8) :: V_BONDI
            END SUBROUTINE PRINT_SINK_PROPERTIES
          END INTERFACE 
        END MODULE PRINT_SINK_PROPERTIES__genmod
