        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE PROLONG__genmod
          INTERFACE 
            SUBROUTINE PROLONG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE PROLONG
          END INTERFACE 
        END MODULE PROLONG__genmod
