        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE PROPAGATE_FLAG__genmod
          INTERFACE 
            SUBROUTINE PROPAGATE_FLAG(NMOVE,NZERO)
              INTEGER(KIND=4) :: NMOVE
              INTEGER(KIND=4) :: NZERO
            END SUBROUTINE PROPAGATE_FLAG
          END INTERFACE 
        END MODULE PROPAGATE_FLAG__genmod
