        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE QUENCHING__genmod
          INTERFACE 
            SUBROUTINE QUENCHING(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE QUENCHING
          END INTERFACE 
        END MODULE QUENCHING__genmod
