        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:58 2016
        MODULE QUICK_SORT__genmod
          INTERFACE 
            SUBROUTINE QUICK_SORT(LIST,ORDER,N)
              INTEGER(KIND=4) :: N
              REAL(KIND=16), INTENT(INOUT) :: LIST(1:N)
              INTEGER(KIND=4), INTENT(OUT) :: ORDER(1:N)
            END SUBROUTINE QUICK_SORT
          END INTERFACE 
        END MODULE QUICK_SORT__genmod
