        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE READ_CLUMPFIND_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_CLUMPFIND_PARAMS
            END SUBROUTINE READ_CLUMPFIND_PARAMS
          END INTERFACE 
        END MODULE READ_CLUMPFIND_PARAMS__genmod
