        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:48 2016
        MODULE READ_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_PARAMS
            END SUBROUTINE READ_PARAMS
          END INTERFACE 
        END MODULE READ_PARAMS__genmod
