        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:17 2016
        MODULE READ_HYDRO_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_HYDRO_PARAMS(NML_OK)
              LOGICAL(KIND=4) :: NML_OK
            END SUBROUTINE READ_HYDRO_PARAMS
          END INTERFACE 
        END MODULE READ_HYDRO_PARAMS__genmod
