        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:20 2016
        MODULE READ_SINK_PARAMS__genmod
          INTERFACE 
            SUBROUTINE READ_SINK_PARAMS
            END SUBROUTINE READ_SINK_PARAMS
          END INTERFACE 
        END MODULE READ_SINK_PARAMS__genmod
