        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:34 2016
        MODULE RECURSIVE_MULTIGRID_COARSE__genmod
          INTERFACE 
            RECURSIVE SUBROUTINE RECURSIVE_MULTIGRID_COARSE(IFINELEVEL, &
     &SAFE)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
              LOGICAL(KIND=4), INTENT(IN) :: SAFE
            END SUBROUTINE RECURSIVE_MULTIGRID_COARSE
          END INTERFACE 
        END MODULE RECURSIVE_MULTIGRID_COARSE__genmod
