        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:29 2016
        MODULE REDUNDANT_NON_1D__genmod
          INTERFACE 
            SUBROUTINE REDUNDANT_NON_1D(LIST,NDATA,NDATA2)
              INTEGER(KIND=4) :: NDATA
              INTEGER(KIND=4) :: LIST(1:NDATA)
              INTEGER(KIND=4) :: NDATA2
            END SUBROUTINE REDUNDANT_NON_1D
          END INTERFACE 
        END MODULE REDUNDANT_NON_1D__genmod
