        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:55 2016
        MODULE REFINE_FINE__genmod
          INTERFACE 
            SUBROUTINE REFINE_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE REFINE_FINE
          END INTERFACE 
        END MODULE REFINE_FINE__genmod
