        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:55 2016
        MODULE REFINE_COARSE__genmod
          INTERFACE 
            SUBROUTINE REFINE_COARSE
            END SUBROUTINE REFINE_COARSE
          END INTERFACE 
        END MODULE REFINE_COARSE__genmod
