        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:17 2016
        MODULE REMOVE_LIST__genmod
          INTERFACE 
            SUBROUTINE REMOVE_LIST(IND_PART,LIST1,OK,NP)
              INTEGER(KIND=4) :: IND_PART(1:32)
              INTEGER(KIND=4) :: LIST1(1:32)
              LOGICAL(KIND=4) :: OK(1:32)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE REMOVE_LIST
          END INTERFACE 
        END MODULE REMOVE_LIST__genmod
