        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:17 2016
        MODULE REMOVE_FREE__genmod
          INTERFACE 
            SUBROUTINE REMOVE_FREE(IND_PART,NP)
              INTEGER(KIND=4) :: IND_PART(1:32)
              INTEGER(KIND=4) :: NP
            END SUBROUTINE REMOVE_FREE
          END INTERFACE 
        END MODULE REMOVE_FREE__genmod
