        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE RESTRICT_MASK_COARSE_REVERSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_MASK_COARSE_REVERSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_MASK_COARSE_REVERSE
          END INTERFACE 
        END MODULE RESTRICT_MASK_COARSE_REVERSE__genmod
