        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE RESTRICT_MASK_FINE_REVERSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_MASK_FINE_REVERSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_MASK_FINE_REVERSE
          END INTERFACE 
        END MODULE RESTRICT_MASK_FINE_REVERSE__genmod
