        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE RESTRICT_RESIDUAL_COARSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_RESIDUAL_COARSE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_RESIDUAL_COARSE
          END INTERFACE 
        END MODULE RESTRICT_RESIDUAL_COARSE__genmod
