        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE RESTRICT__genmod
          INTERFACE 
            SUBROUTINE RESTRICT(IND_GRID,NGRID,ILEVEL,MULTIGRID)
              INTEGER(KIND=4) :: IND_GRID(1:32)
              INTEGER(KIND=4) :: NGRID
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: MULTIGRID
            END SUBROUTINE RESTRICT
          END INTERFACE 
        END MODULE RESTRICT__genmod
