        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:33 2016
        MODULE RESTRICTION_FINE__genmod
          INTERFACE 
            SUBROUTINE RESTRICTION_FINE(ILEVEL,MULTIGRID)
              INTEGER(KIND=4) :: ILEVEL
              LOGICAL(KIND=4) :: MULTIGRID
            END SUBROUTINE RESTRICTION_FINE
          END INTERFACE 
        END MODULE RESTRICTION_FINE__genmod
