        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE RESTRICT_MASK_COARSE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_MASK_COARSE(IFINELEVEL,ALLMASKED)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
              LOGICAL(KIND=4), INTENT(OUT) :: ALLMASKED
            END SUBROUTINE RESTRICT_MASK_COARSE
          END INTERFACE 
        END MODULE RESTRICT_MASK_COARSE__genmod
