        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE RESTRICT_RESIDUAL_FINE__genmod
          INTERFACE 
            SUBROUTINE RESTRICT_RESIDUAL_FINE(IFINELEVEL)
              INTEGER(KIND=4), INTENT(IN) :: IFINELEVEL
            END SUBROUTINE RESTRICT_RESIDUAL_FINE
          END INTERFACE 
        END MODULE RESTRICT_RESIDUAL_FINE__genmod
