        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:24 2016
        MODULE RHO_ONLY_LEVEL__genmod
          INTERFACE 
            SUBROUTINE RHO_ONLY_LEVEL(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RHO_ONLY_LEVEL
          END INTERFACE 
        END MODULE RHO_ONLY_LEVEL__genmod
