        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:11 2016
        MODULE RHO_FROM_CURRENT_LEVEL__genmod
          INTERFACE 
            SUBROUTINE RHO_FROM_CURRENT_LEVEL(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE RHO_FROM_CURRENT_LEVEL
          END INTERFACE 
        END MODULE RHO_FROM_CURRENT_LEVEL__genmod
