        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE SAVEGADGET__genmod
          INTERFACE 
            SUBROUTINE SAVEGADGET(FILENAME)
              CHARACTER(LEN=80) :: FILENAME
            END SUBROUTINE SAVEGADGET
          END INTERFACE 
        END MODULE SAVEGADGET__genmod
