        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:35 2016
        MODULE SET_SCAN_FLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE SET_SCAN_FLAG_FINE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE SET_SCAN_FLAG_FINE
          END INTERFACE 
        END MODULE SET_SCAN_FLAG_FINE__genmod
