        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:36 2016
        MODULE SET_SCAN_FLAG_COARSE__genmod
          INTERFACE 
            SUBROUTINE SET_SCAN_FLAG_COARSE(ILEVEL)
              INTEGER(KIND=4), INTENT(IN) :: ILEVEL
            END SUBROUTINE SET_SCAN_FLAG_COARSE
          END INTERFACE 
        END MODULE SET_SCAN_FLAG_COARSE__genmod
