        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:38 2016
        MODULE SET_SIGNAL_HANDLER__genmod
          INTERFACE 
            SUBROUTINE SET_SIGNAL_HANDLER
            END SUBROUTINE SET_SIGNAL_HANDLER
          END INTERFACE 
        END MODULE SET_SIGNAL_HANDLER__genmod
