        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:17 2016
        MODULE STAR_FORMATION__genmod
          INTERFACE 
            SUBROUTINE STAR_FORMATION(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE STAR_FORMATION
          END INTERFACE 
        END MODULE STAR_FORMATION__genmod
