        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:28 2016
        MODULE STELLAR_WINDS_FINE__genmod
          INTERFACE 
            SUBROUTINE STELLAR_WINDS_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE STELLAR_WINDS_FINE
          END INTERFACE 
        END MODULE STELLAR_WINDS_FINE__genmod
