        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE SURFACE_INT__genmod
          INTERFACE 
            SUBROUTINE SURFACE_INT
            END SUBROUTINE SURFACE_INT
          END INTERFACE 
        END MODULE SURFACE_INT__genmod
