        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE SURFACE_INT_NP__genmod
          INTERFACE 
            SUBROUTINE SURFACE_INT_NP(IND_CELL,NP,ILEVEL)
              INTEGER(KIND=4) :: IND_CELL(1:32)
              INTEGER(KIND=4) :: NP
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SURFACE_INT_NP
          END INTERFACE 
        END MODULE SURFACE_INT_NP__genmod
