        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:09 2016
        MODULE SYNCHYDROFINE1__genmod
          INTERFACE 
            SUBROUTINE SYNCHYDROFINE1(IND_CELL,NCELL,DTEFF)
              INTEGER(KIND=4) :: IND_CELL(1:32)
              INTEGER(KIND=4) :: NCELL
              REAL(KIND=8) :: DTEFF
            END SUBROUTINE SYNCHYDROFINE1
          END INTERFACE 
        END MODULE SYNCHYDROFINE1__genmod
