        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:09 2016
        MODULE SYNCHRO_HYDRO_FINE__genmod
          INTERFACE 
            SUBROUTINE SYNCHRO_HYDRO_FINE(ILEVEL,DTEFF)
              INTEGER(KIND=4) :: ILEVEL
              REAL(KIND=8) :: DTEFF
            END SUBROUTINE SYNCHRO_HYDRO_FINE
          END INTERFACE 
        END MODULE SYNCHRO_HYDRO_FINE__genmod
