        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:13 2016
        MODULE SYNCHRO_FINE__genmod
          INTERFACE 
            SUBROUTINE SYNCHRO_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE SYNCHRO_FINE
          END INTERFACE 
        END MODULE SYNCHRO_FINE__genmod
