        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE TEST_FLAG__genmod
          INTERFACE 
            SUBROUTINE TEST_FLAG(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE TEST_FLAG
          END INTERFACE 
        END MODULE TEST_FLAG__genmod
