        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:22 2016
        MODULE THERMAL_FEEDBACK__genmod
          INTERFACE 
            SUBROUTINE THERMAL_FEEDBACK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE THERMAL_FEEDBACK
          END INTERFACE 
        END MODULE THERMAL_FEEDBACK__genmod
