        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:27 2016
        MODULE TRIM_CLUMPS__genmod
          INTERFACE 
            SUBROUTINE TRIM_CLUMPS
            END SUBROUTINE TRIM_CLUMPS
          END INTERFACE 
        END MODULE TRIM_CLUMPS__genmod
