        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:11 2016
        MODULE TSC_FROM_MULTIPOLE__genmod
          INTERFACE 
            SUBROUTINE TSC_FROM_MULTIPOLE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE TSC_FROM_MULTIPOLE
          END INTERFACE 
        END MODULE TSC_FROM_MULTIPOLE__genmod
