        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:19 2016
        MODULE UPDATE_SINK__genmod
          INTERFACE 
            SUBROUTINE UPDATE_SINK(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE UPDATE_SINK
          END INTERFACE 
        END MODULE UPDATE_SINK__genmod
