        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE UPDATE_TIME__genmod
          INTERFACE 
            SUBROUTINE UPDATE_TIME(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE UPDATE_TIME
          END INTERFACE 
        END MODULE UPDATE_TIME__genmod
