        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:52 2016
        MODULE USERFLAG_FINE__genmod
          INTERFACE 
            SUBROUTINE USERFLAG_FINE(ILEVEL)
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE USERFLAG_FINE
          END INTERFACE 
        END MODULE USERFLAG_FINE__genmod
