        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE VIRTUAL_PEAK_INT__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_PEAK_INT(XX,ACTION)
              USE CLFIND_COMMONS
              USE AMR_COMMONS
              INTEGER(KIND=4) :: XX(1:NPEAKS_MAX)
              CHARACTER(LEN=3) :: ACTION
            END SUBROUTINE VIRTUAL_PEAK_INT
          END INTERFACE 
        END MODULE VIRTUAL_PEAK_INT__genmod
