        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:19 2016
        MODULE VIRTUAL_TREE_FINE__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_TREE_FINE(ILEVEL)
              USE AMR_COMMONS
              INTEGER(KIND=4) :: ILEVEL
            END SUBROUTINE VIRTUAL_TREE_FINE
          END INTERFACE 
        END MODULE VIRTUAL_TREE_FINE__genmod
