        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE VIRTUAL_SADDLE_MAX__genmod
          INTERFACE 
            SUBROUTINE VIRTUAL_SADDLE_MAX
              USE AMR_COMMONS
            END SUBROUTINE VIRTUAL_SADDLE_MAX
          END INTERFACE 
        END MODULE VIRTUAL_SADDLE_MAX__genmod
