        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE WRITE_CLUMP_PROPERTIES__genmod
          INTERFACE 
            SUBROUTINE WRITE_CLUMP_PROPERTIES(TO_FILE)
              USE CLFIND_COMMONS
              LOGICAL(KIND=4) :: TO_FILE
            END SUBROUTINE WRITE_CLUMP_PROPERTIES
          END INTERFACE 
        END MODULE WRITE_CLUMP_PROPERTIES__genmod
