        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:01 2016
        MODULE WRITE_SCREEN__genmod
          INTERFACE 
            SUBROUTINE WRITE_SCREEN
              USE AMR_COMMONS
            END SUBROUTINE WRITE_SCREEN
          END INTERFACE 
        END MODULE WRITE_SCREEN__genmod
