        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 11:03:16 2016
        MODULE WRITE_GITINFO__genmod
          INTERFACE 
            SUBROUTINE WRITE_GITINFO
            END SUBROUTINE WRITE_GITINFO
          END INTERFACE 
        END MODULE WRITE_GITINFO__genmod
