        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:14:25 2016
        MODULE WRITE_CLUMP_MAP__genmod
          INTERFACE 
            SUBROUTINE WRITE_CLUMP_MAP
            END SUBROUTINE WRITE_CLUMP_MAP
          END INTERFACE 
        END MODULE WRITE_CLUMP_MAP__genmod
