        !COMPILER-GENERATED INTERFACE MODULE: Tue Jul 19 00:13:51 2016
        MODULE WRITEMEM__genmod
          INTERFACE 
            SUBROUTINE WRITEMEM(USEDMEM)
              REAL(KIND=4) :: USEDMEM
            END SUBROUTINE WRITEMEM
          END INTERFACE 
        END MODULE WRITEMEM__genmod
